/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.saltsoft;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {
    System.out.println(new App().getGreeting());
    ReadFile f = new ReadFile();
    f.readLinesFromFile("U:\\sum\\ExamplesNewest\\src\\main\\java\\pl\\saltsoft\\App.java");
    f.writeLinesFromFile("readme.md");
    }

}
